# Generated by Django 4.2 on 2023-04-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_alter_comment_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="body",
            field=models.CharField(default=None, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
