# Generated by Django 4.2 on 2023-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0003_comment_body_comment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
