# Generated by Django 4.2 on 2023-04-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0004_alter_comment_date_alter_comment_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
